# Generated by Django 3.0.2 on 2020-01-26 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='veg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.CharField(max_length=1000)),
                ('minerals', models.CharField(max_length=500)),
                ('vitamins', models.CharField(max_length=500)),
                ('recipe_photo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='veg_people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('name_of_people', models.CharField(max_length=500)),
                ('Veg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.veg')),
            ],
        ),
    ]
